# Generated by Django 5.2.6 on 2025-11-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
    ]
